// OrionProject.Vue.UI/src/components/NavBar.vue
<template>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark ps-5">
        <router-link class="navbar-brand" :to="{ name: 'Home' }">
            OrionProject
        </router-link>
  
        <div class="navbar-collapse">
          <div class="navbar-nav">
            <router-link class="nav-item nav-link" :to="{ name: 'Clients' }">
                Clients
            </router-link>
            <router-link class="nav-item nav-link" :to="{ name: 'Addresses' }">
                Addresses
            </router-link>
          </div>
        </div>
      </nav>
</template>

<script>
    export default {
        name: 'NavBar'
    }
</script>

// OrionProject.React.UI/src/components/NavBar.js
import React from 'react';
import { Link, NavLink } from 'react-router-dom';

export const NavBar = () => {
    return (
        <nav className="navbar navbar-expand-sm navbar-dark bg-dark ps-5">
        <Link className="navbar-brand" to="/">
          OrionProject
        </Link>
  
        <div className="navbar-collapse">
          <div className="navbar-nav">
            <NavLink className="nav-item nav-link" to='/clients'>
                Clients
            </NavLink>
            <NavLink className="nav-item nav-link" to='/addresses'>
                Addresses
            </NavLink>
          </div>
        </div>
      </nav>
    )
}
